### ISSUE TITLE
Todo list 15 October

### ISSUE THREAD

**Issue by dill** [DistanceDevelopment/spatial-workshops#24]
Generated from Skype conversation Jason and Dave

* [x] mail-out on 20th
  * [x] pre-workshop survey
  * [x] Make sure DEL folks send out info for:
    * phone numbers
    * restaurants (and transport)
    * transport from hotel to Nic School
  * [x] link to instructions for computing (not necessary!)
  * [x] link to course website
* [x] *Jason* look through slides (PDFs)
* [x] Campus circulator busses -- dinner plans?
* [x] *Dave* write practicals
* [x] *Jason* write practicals
* [x] *Jason* slides
* [x] confirm that user home spaces will be persistent
* [x] Check data requirements per practical and streamlined-ness of materials
* [x] Division of time between Lab 1045-1215 Wed and Class 1315-1445
* [ ] Nomenclature/jargon/disambiguation
* [x] Additonal mailout
  * [ ] ~~*Dave* practice RMarkdown file (Thursday)~~
  * [x] *Dave* link to PDFs of lectures (wait until Thursday?)
