### ISSUE TITLE
workshop todo list

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/spatial-workshops#48]
- [ ] website organisation
    - what materials must participants have
    - email participants by date x (25/26 July) 
- [ ] functional website
- [ ] solutions for spatial exercises
- [ ] Monday morning materials needed
- [ ] installation instructions  --- get this ahead of time (Eric can prep)
- [ ] daily schedule

**Comment by dill** [comment]
The start of a site is at 
http://distancesampling.org/workshops/stand-intermed-2017/

**Comment by erex** [comment]
need to place practical materials onto course website for
- mrds exercise
    - think that is only Crabbie MRDS and GolfteeExercise D7 projects (from 2016)
- DSsim exercise
     - there is a D7 project, but also quite a collection of R objects and shape files for surveys
